# =============================
# ✅ Site settings
# =============================
title: "Kaylie's Data Portfolio"
subtitle: "Turning Data into Meaningful Stories"
email: le.thitr@northeastern.edu
description: >-
  Welcome to my portfolio! I’m passionate about data analysis, visualization,
  and statistical modeling. With a background in research, communication, and marketing,
  I apply technical skills to solve real-world problems across education, business, and society.
baseurl: "" # keep empty if deploying at root
url: "https://yourusername.github.io"  # Replace with your GitHub Pages URL

author: "Kaylie Le"
street_address: "123 Harvard Street"
city: "Boston"
state: "MA"
zip_code: "02115"
country: "United States of America"
phone: "(617) 555-5555"

# =============================
#  Homepage / Tiles
# =============================
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# =============================
#  Socials
# =============================
socials:
  GitHub: https://github.com/yourusername
  LinkedIn: https://www.linkedin.com/in/my-kaylie-le-667381254/
  Email: mailto:le.thitr@northeastern.edu

# =============================
#  Build settings
# =============================
markdown: kramdown

sass:
  style: compressed

# Include custom CSS for extra styles
site-css:
  - "/assets/css/custom-styles.css"

# =============================
#  Files to exclude from build
# =============================
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
